# .github/workflows/build-and-deploy-cli.yml

name: Build and Deploy to ACI via CLI

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to ACR
      run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/myapp:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.ACR_NAME }}.azurecr.io/myapp:latest

    - name: Azure CLI Login (Assumes GitHub-hosted runner is already authenticated)
      run: az account show

    - name: Deploy to ACI using az CLI
      run: |
        az container create \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --name myapp-container-${{ github.run_number }} \
          --image ${{ secrets.ACR_NAME }}.azurecr.io/myapp:latest \
          --registry-login-server ${{ secrets.ACR_NAME }}.azurecr.io \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --dns-name-label myapp-${{ github.run_number }} \
          --ports 80 \
          --location westus
