# .github/workflows/docker-build-push.yml
name: Build and Push Docker Image to ACR

on:
  push:
    branches: [ main ]  # or master, depending on your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to ACR
      run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/myapp:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.ACR_NAME }}.azurecr.io/myapp:latest
